name: UI-Evaluation-Dashboard
channels:
  - defaults
  - pytorch
dependencies:
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - numpy
  - pillow
  - scikit-learn
  - opencv
  - conda-forge::fastapi